runtime: python27
api_version: 1
threadsafe: True

handlers:
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))

- url: /.*
  script: main.app

libraries:
- name: lxml
  version: latest

automatic_scaling:
  max_idle_instances: 2
  max_concurrent_requests: 12

