runtime: python27
api_version: 1
threadsafe: True

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
- url: /blobstore.*
  script: blobstore.app

libraries:
- name: lxml
  version: latest

builtins:
- deferred: on
